// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/reactions.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReactionRequest) Reset() {
	*x = CreateReactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reactions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReactionRequest) ProtoMessage() {}

func (x *CreateReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reactions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReactionRequest.ProtoReflect.Descriptor instead.
func (*CreateReactionRequest) Descriptor() ([]byte, []int) {
	return file_api_reactions_proto_rawDescGZIP(), []int{0}
}

type CreateReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReactionResponse) Reset() {
	*x = CreateReactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reactions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReactionResponse) ProtoMessage() {}

func (x *CreateReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reactions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReactionResponse.ProtoReflect.Descriptor instead.
func (*CreateReactionResponse) Descriptor() ([]byte, []int) {
	return file_api_reactions_proto_rawDescGZIP(), []int{1}
}

type GetReationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReationRequest) Reset() {
	*x = GetReationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reactions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReationRequest) ProtoMessage() {}

func (x *GetReationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reactions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReationRequest.ProtoReflect.Descriptor instead.
func (*GetReationRequest) Descriptor() ([]byte, []int) {
	return file_api_reactions_proto_rawDescGZIP(), []int{2}
}

type GetReationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReationResponse) Reset() {
	*x = GetReationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reactions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReationResponse) ProtoMessage() {}

func (x *GetReationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reactions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReationResponse.ProtoReflect.Descriptor instead.
func (*GetReationResponse) Descriptor() ([]byte, []int) {
	return file_api_reactions_proto_rawDescGZIP(), []int{3}
}

type UpdateReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReactionRequest) Reset() {
	*x = UpdateReactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reactions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReactionRequest) ProtoMessage() {}

func (x *UpdateReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reactions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateReactionRequest) Descriptor() ([]byte, []int) {
	return file_api_reactions_proto_rawDescGZIP(), []int{4}
}

type UpdateReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReactionResponse) Reset() {
	*x = UpdateReactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reactions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReactionResponse) ProtoMessage() {}

func (x *UpdateReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reactions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReactionResponse.ProtoReflect.Descriptor instead.
func (*UpdateReactionResponse) Descriptor() ([]byte, []int) {
	return file_api_reactions_proto_rawDescGZIP(), []int{5}
}

type DeleteReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReactionRequest) Reset() {
	*x = DeleteReactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reactions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionRequest) ProtoMessage() {}

func (x *DeleteReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reactions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteReactionRequest) Descriptor() ([]byte, []int) {
	return file_api_reactions_proto_rawDescGZIP(), []int{6}
}

type DeleteReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReactionResponse) Reset() {
	*x = DeleteReactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reactions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionResponse) ProtoMessage() {}

func (x *DeleteReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reactions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteReactionResponse) Descriptor() ([]byte, []int) {
	return file_api_reactions_proto_rawDescGZIP(), []int{7}
}

var File_api_reactions_proto protoreflect.FileDescriptor

var file_api_reactions_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66,
	0x65, 0x65, 0x64, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x61, 0x70,
	0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_reactions_proto_rawDescOnce sync.Once
	file_api_reactions_proto_rawDescData = file_api_reactions_proto_rawDesc
)

func file_api_reactions_proto_rawDescGZIP() []byte {
	file_api_reactions_proto_rawDescOnce.Do(func() {
		file_api_reactions_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_reactions_proto_rawDescData)
	})
	return file_api_reactions_proto_rawDescData
}

var file_api_reactions_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_reactions_proto_goTypes = []interface{}{
	(*CreateReactionRequest)(nil),  // 0: syntoks_feed.CreateReactionRequest
	(*CreateReactionResponse)(nil), // 1: syntoks_feed.CreateReactionResponse
	(*GetReationRequest)(nil),      // 2: syntoks_feed.GetReationRequest
	(*GetReationResponse)(nil),     // 3: syntoks_feed.GetReationResponse
	(*UpdateReactionRequest)(nil),  // 4: syntoks_feed.UpdateReactionRequest
	(*UpdateReactionResponse)(nil), // 5: syntoks_feed.UpdateReactionResponse
	(*DeleteReactionRequest)(nil),  // 6: syntoks_feed.DeleteReactionRequest
	(*DeleteReactionResponse)(nil), // 7: syntoks_feed.DeleteReactionResponse
}
var file_api_reactions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_reactions_proto_init() }
func file_api_reactions_proto_init() {
	if File_api_reactions_proto != nil {
		return
	}
	file_api_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_reactions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reactions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reactions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reactions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reactions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reactions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reactions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reactions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_reactions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_reactions_proto_goTypes,
		DependencyIndexes: file_api_reactions_proto_depIdxs,
		MessageInfos:      file_api_reactions_proto_msgTypes,
	}.Build()
	File_api_reactions_proto = out.File
	file_api_reactions_proto_rawDesc = nil
	file_api_reactions_proto_goTypes = nil
	file_api_reactions_proto_depIdxs = nil
}
