// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{1}
}

var File_api_service_proto protoreflect.FileDescriptor

var file_api_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65,
	0x64, 0x1a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x14, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x61, 0x70,
	0x69, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a,
	0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xdc, 0x14, 0x0a,
	0x05, 0x46, 0x65, 0x65, 0x64, 0x73, 0x12, 0x54, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x20, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b,
	0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x13,
	0x41, 0x64, 0x64, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x12, 0x28, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65,
	0x65, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e,
	0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x41, 0x64, 0x64,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x20, 0x2e, 0x73, 0x79, 0x6e, 0x74,
	0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x79,
	0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x72, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x42,
	0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x12, 0x2a, 0x2e, 0x73, 0x79, 0x6e, 0x74,
	0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x42, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x42, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x23, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73,
	0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x79,
	0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x23, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x79, 0x6e,
	0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x12, 0x1f, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64,
	0x12, 0x1c, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x66, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x26, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66,
	0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73,
	0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x65, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x65, 0x65, 0x64, 0x12, 0x1f, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73,
	0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x12, 0x1f, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f,
	0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x79, 0x6e, 0x74,
	0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x25, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f,
	0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x21, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65,
	0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1e, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f,
	0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f,
	0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x21, 0x2e, 0x73, 0x79,
	0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x21, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66,
	0x65, 0x65, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b,
	0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x23, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66,
	0x65, 0x65, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x73, 0x79,
	0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65,
	0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x29, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x79,
	0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x73, 0x79,
	0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x73, 0x79, 0x6e,
	0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x12, 0x27, 0x2e,
	0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73,
	0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x60, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e,
	0x67, 0x46, 0x65, 0x65, 0x64, 0x12, 0x24, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x79,
	0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x7e, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x2e, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2f, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x12, 0x27, 0x2e, 0x73, 0x79, 0x6e,
	0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65,
	0x65, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e,
	0x67, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x69, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e,
	0x67, 0x46, 0x65, 0x65, 0x64, 0x12, 0x27, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x04, 0x50, 0x69,
	0x6e, 0x67, 0x12, 0x19, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65,
	0x64, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x73, 0x79, 0x6e, 0x74, 0x6f, 0x6b, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_service_proto_rawDescOnce sync.Once
	file_api_service_proto_rawDescData = file_api_service_proto_rawDesc
)

func file_api_service_proto_rawDescGZIP() []byte {
	file_api_service_proto_rawDescOnce.Do(func() {
		file_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_service_proto_rawDescData)
	})
	return file_api_service_proto_rawDescData
}

var file_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_service_proto_goTypes = []interface{}{
	(*PingRequest)(nil),                       // 0: syntoks_feed.PingRequest
	(*PingResponse)(nil),                      // 1: syntoks_feed.PingResponse
	(*AddActivityRequest)(nil),                // 2: syntoks_feed.AddActivityRequest
	(*AddExistingActivityRequest)(nil),        // 3: syntoks_feed.AddExistingActivityRequest
	(*GetActivityRequest)(nil),                // 4: syntoks_feed.GetActivityRequest
	(*GetActivityByObjectIDRequest)(nil),      // 5: syntoks_feed.GetActivityByObjectIDRequest
	(*UpdateActivityRequest)(nil),             // 6: syntoks_feed.UpdateActivityRequest
	(*DeleteActivityRequest)(nil),             // 7: syntoks_feed.DeleteActivityRequest
	(*CreateFeedRequest)(nil),                 // 8: syntoks_feed.CreateFeedRequest
	(*GetFeedRequest)(nil),                    // 9: syntoks_feed.GetFeedRequest
	(*GetFeedActivitiesRequest)(nil),          // 10: syntoks_feed.GetFeedActivitiesRequest
	(*UpdateFeedRequest)(nil),                 // 11: syntoks_feed.UpdateFeedRequest
	(*DeleteFeedRequest)(nil),                 // 12: syntoks_feed.DeleteFeedRequest
	(*CreateCollectionRequest)(nil),           // 13: syntoks_feed.CreateCollectionRequest
	(*CreateObjectRequest)(nil),               // 14: syntoks_feed.CreateObjectRequest
	(*GetObjectRequest)(nil),                  // 15: syntoks_feed.GetObjectRequest
	(*UpdateObjectRequest)(nil),               // 16: syntoks_feed.UpdateObjectRequest
	(*DeleteObjectRequest)(nil),               // 17: syntoks_feed.DeleteObjectRequest
	(*CreateReactionRequest)(nil),             // 18: syntoks_feed.CreateReactionRequest
	(*AddReactionRequest)(nil),                // 19: syntoks_feed.AddReactionRequest
	(*GetReactionRequest)(nil),                // 20: syntoks_feed.GetReactionRequest
	(*GetActivityReactionsRequest)(nil),       // 21: syntoks_feed.GetActivityReactionsRequest
	(*UpdateReactionRequest)(nil),             // 22: syntoks_feed.UpdateReactionRequest
	(*DeleteReactionRequest)(nil),             // 23: syntoks_feed.DeleteReactionRequest
	(*CreateGroupingFeedRequest)(nil),         // 24: syntoks_feed.CreateGroupingFeedRequest
	(*GetGroupingFeedRequest)(nil),            // 25: syntoks_feed.GetGroupingFeedRequest
	(*GetGroupingFeedActivitiesRequest)(nil),  // 26: syntoks_feed.GetGroupingFeedActivitiesRequest
	(*UpdateGroupingFeedRequest)(nil),         // 27: syntoks_feed.UpdateGroupingFeedRequest
	(*DeleteGroupingFeedRequest)(nil),         // 28: syntoks_feed.DeleteGroupingFeedRequest
	(*AddActivityResponse)(nil),               // 29: syntoks_feed.AddActivityResponse
	(*AddExistingActivityResponse)(nil),       // 30: syntoks_feed.AddExistingActivityResponse
	(*GetActivityResponse)(nil),               // 31: syntoks_feed.GetActivityResponse
	(*GetActivityByObjectIDResponse)(nil),     // 32: syntoks_feed.GetActivityByObjectIDResponse
	(*UpdateActivityResponse)(nil),            // 33: syntoks_feed.UpdateActivityResponse
	(*DeleteActivityResponse)(nil),            // 34: syntoks_feed.DeleteActivityResponse
	(*CreateFeedResponse)(nil),                // 35: syntoks_feed.CreateFeedResponse
	(*GetFeedResponse)(nil),                   // 36: syntoks_feed.GetFeedResponse
	(*GetFeedActivitiesResponse)(nil),         // 37: syntoks_feed.GetFeedActivitiesResponse
	(*UpdateFeedResponse)(nil),                // 38: syntoks_feed.UpdateFeedResponse
	(*DeleteFeedResponse)(nil),                // 39: syntoks_feed.DeleteFeedResponse
	(*CreateCollectionResponse)(nil),          // 40: syntoks_feed.CreateCollectionResponse
	(*CreateObjectResponse)(nil),              // 41: syntoks_feed.CreateObjectResponse
	(*GetObjectResponse)(nil),                 // 42: syntoks_feed.GetObjectResponse
	(*UpdateObjectResponse)(nil),              // 43: syntoks_feed.UpdateObjectResponse
	(*DeleteObjectResponse)(nil),              // 44: syntoks_feed.DeleteObjectResponse
	(*CreateReactionResponse)(nil),            // 45: syntoks_feed.CreateReactionResponse
	(*AddReactionResponse)(nil),               // 46: syntoks_feed.AddReactionResponse
	(*GetReactionResponse)(nil),               // 47: syntoks_feed.GetReactionResponse
	(*GetActivityReactionsResponse)(nil),      // 48: syntoks_feed.GetActivityReactionsResponse
	(*UpdateReactionResponse)(nil),            // 49: syntoks_feed.UpdateReactionResponse
	(*DeleteReactionResponse)(nil),            // 50: syntoks_feed.DeleteReactionResponse
	(*CreateGroupingFeedResponse)(nil),        // 51: syntoks_feed.CreateGroupingFeedResponse
	(*GetGroupingFeedResponse)(nil),           // 52: syntoks_feed.GetGroupingFeedResponse
	(*GetGroupingFeedActivitiesResponse)(nil), // 53: syntoks_feed.GetGroupingFeedActivitiesResponse
	(*UpdateGroupingFeedResponse)(nil),        // 54: syntoks_feed.UpdateGroupingFeedResponse
	(*DeleteGroupingFeedResponse)(nil),        // 55: syntoks_feed.DeleteGroupingFeedResponse
}
var file_api_service_proto_depIdxs = []int32{
	2,  // 0: syntoks_feed.Feeds.AddActivity:input_type -> syntoks_feed.AddActivityRequest
	3,  // 1: syntoks_feed.Feeds.AddExistingActivity:input_type -> syntoks_feed.AddExistingActivityRequest
	4,  // 2: syntoks_feed.Feeds.GetActivity:input_type -> syntoks_feed.GetActivityRequest
	5,  // 3: syntoks_feed.Feeds.GetActivityByObjectID:input_type -> syntoks_feed.GetActivityByObjectIDRequest
	6,  // 4: syntoks_feed.Feeds.UpdateActivity:input_type -> syntoks_feed.UpdateActivityRequest
	7,  // 5: syntoks_feed.Feeds.DeleteActivity:input_type -> syntoks_feed.DeleteActivityRequest
	8,  // 6: syntoks_feed.Feeds.CreateFeed:input_type -> syntoks_feed.CreateFeedRequest
	9,  // 7: syntoks_feed.Feeds.GetFeed:input_type -> syntoks_feed.GetFeedRequest
	10, // 8: syntoks_feed.Feeds.GetFeedActivities:input_type -> syntoks_feed.GetFeedActivitiesRequest
	11, // 9: syntoks_feed.Feeds.UpdateFeed:input_type -> syntoks_feed.UpdateFeedRequest
	12, // 10: syntoks_feed.Feeds.DeleteFeed:input_type -> syntoks_feed.DeleteFeedRequest
	13, // 11: syntoks_feed.Feeds.CreateCollection:input_type -> syntoks_feed.CreateCollectionRequest
	14, // 12: syntoks_feed.Feeds.CreateObject:input_type -> syntoks_feed.CreateObjectRequest
	15, // 13: syntoks_feed.Feeds.GetObject:input_type -> syntoks_feed.GetObjectRequest
	16, // 14: syntoks_feed.Feeds.UpdateObject:input_type -> syntoks_feed.UpdateObjectRequest
	17, // 15: syntoks_feed.Feeds.DeleteObject:input_type -> syntoks_feed.DeleteObjectRequest
	18, // 16: syntoks_feed.Feeds.CreateReaction:input_type -> syntoks_feed.CreateReactionRequest
	19, // 17: syntoks_feed.Feeds.AddReaction:input_type -> syntoks_feed.AddReactionRequest
	20, // 18: syntoks_feed.Feeds.GetReaction:input_type -> syntoks_feed.GetReactionRequest
	21, // 19: syntoks_feed.Feeds.GetActivityReactions:input_type -> syntoks_feed.GetActivityReactionsRequest
	22, // 20: syntoks_feed.Feeds.UpdateReaction:input_type -> syntoks_feed.UpdateReactionRequest
	23, // 21: syntoks_feed.Feeds.DeleteReaction:input_type -> syntoks_feed.DeleteReactionRequest
	24, // 22: syntoks_feed.Feeds.CreateGroupingFeed:input_type -> syntoks_feed.CreateGroupingFeedRequest
	25, // 23: syntoks_feed.Feeds.GetGroupingFeed:input_type -> syntoks_feed.GetGroupingFeedRequest
	26, // 24: syntoks_feed.Feeds.GetGroupingFeedActivities:input_type -> syntoks_feed.GetGroupingFeedActivitiesRequest
	27, // 25: syntoks_feed.Feeds.UpdateGroupingFeed:input_type -> syntoks_feed.UpdateGroupingFeedRequest
	28, // 26: syntoks_feed.Feeds.DeleteGroupingFeed:input_type -> syntoks_feed.DeleteGroupingFeedRequest
	0,  // 27: syntoks_feed.Feeds.Ping:input_type -> syntoks_feed.PingRequest
	29, // 28: syntoks_feed.Feeds.AddActivity:output_type -> syntoks_feed.AddActivityResponse
	30, // 29: syntoks_feed.Feeds.AddExistingActivity:output_type -> syntoks_feed.AddExistingActivityResponse
	31, // 30: syntoks_feed.Feeds.GetActivity:output_type -> syntoks_feed.GetActivityResponse
	32, // 31: syntoks_feed.Feeds.GetActivityByObjectID:output_type -> syntoks_feed.GetActivityByObjectIDResponse
	33, // 32: syntoks_feed.Feeds.UpdateActivity:output_type -> syntoks_feed.UpdateActivityResponse
	34, // 33: syntoks_feed.Feeds.DeleteActivity:output_type -> syntoks_feed.DeleteActivityResponse
	35, // 34: syntoks_feed.Feeds.CreateFeed:output_type -> syntoks_feed.CreateFeedResponse
	36, // 35: syntoks_feed.Feeds.GetFeed:output_type -> syntoks_feed.GetFeedResponse
	37, // 36: syntoks_feed.Feeds.GetFeedActivities:output_type -> syntoks_feed.GetFeedActivitiesResponse
	38, // 37: syntoks_feed.Feeds.UpdateFeed:output_type -> syntoks_feed.UpdateFeedResponse
	39, // 38: syntoks_feed.Feeds.DeleteFeed:output_type -> syntoks_feed.DeleteFeedResponse
	40, // 39: syntoks_feed.Feeds.CreateCollection:output_type -> syntoks_feed.CreateCollectionResponse
	41, // 40: syntoks_feed.Feeds.CreateObject:output_type -> syntoks_feed.CreateObjectResponse
	42, // 41: syntoks_feed.Feeds.GetObject:output_type -> syntoks_feed.GetObjectResponse
	43, // 42: syntoks_feed.Feeds.UpdateObject:output_type -> syntoks_feed.UpdateObjectResponse
	44, // 43: syntoks_feed.Feeds.DeleteObject:output_type -> syntoks_feed.DeleteObjectResponse
	45, // 44: syntoks_feed.Feeds.CreateReaction:output_type -> syntoks_feed.CreateReactionResponse
	46, // 45: syntoks_feed.Feeds.AddReaction:output_type -> syntoks_feed.AddReactionResponse
	47, // 46: syntoks_feed.Feeds.GetReaction:output_type -> syntoks_feed.GetReactionResponse
	48, // 47: syntoks_feed.Feeds.GetActivityReactions:output_type -> syntoks_feed.GetActivityReactionsResponse
	49, // 48: syntoks_feed.Feeds.UpdateReaction:output_type -> syntoks_feed.UpdateReactionResponse
	50, // 49: syntoks_feed.Feeds.DeleteReaction:output_type -> syntoks_feed.DeleteReactionResponse
	51, // 50: syntoks_feed.Feeds.CreateGroupingFeed:output_type -> syntoks_feed.CreateGroupingFeedResponse
	52, // 51: syntoks_feed.Feeds.GetGroupingFeed:output_type -> syntoks_feed.GetGroupingFeedResponse
	53, // 52: syntoks_feed.Feeds.GetGroupingFeedActivities:output_type -> syntoks_feed.GetGroupingFeedActivitiesResponse
	54, // 53: syntoks_feed.Feeds.UpdateGroupingFeed:output_type -> syntoks_feed.UpdateGroupingFeedResponse
	55, // 54: syntoks_feed.Feeds.DeleteGroupingFeed:output_type -> syntoks_feed.DeleteGroupingFeedResponse
	1,  // 55: syntoks_feed.Feeds.Ping:output_type -> syntoks_feed.PingResponse
	28, // [28:56] is the sub-list for method output_type
	0,  // [0:28] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	file_api_reactions_proto_init()
	file_api_groupingFeeds_proto_init()
	file_api_activities_proto_init()
	file_api_collections_proto_init()
	file_api_feeds_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
		MessageInfos:      file_api_service_proto_msgTypes,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_rawDesc = nil
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FeedsClient is the client API for Feeds service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedsClient interface {
	// activities.proto
	AddActivity(ctx context.Context, in *AddActivityRequest, opts ...grpc.CallOption) (*AddActivityResponse, error)
	AddExistingActivity(ctx context.Context, in *AddExistingActivityRequest, opts ...grpc.CallOption) (*AddExistingActivityResponse, error)
	GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*GetActivityResponse, error)
	GetActivityByObjectID(ctx context.Context, in *GetActivityByObjectIDRequest, opts ...grpc.CallOption) (*GetActivityByObjectIDResponse, error)
	UpdateActivity(ctx context.Context, in *UpdateActivityRequest, opts ...grpc.CallOption) (*UpdateActivityResponse, error)
	DeleteActivity(ctx context.Context, in *DeleteActivityRequest, opts ...grpc.CallOption) (*DeleteActivityResponse, error)
	// feeds.proto
	CreateFeed(ctx context.Context, in *CreateFeedRequest, opts ...grpc.CallOption) (*CreateFeedResponse, error)
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error)
	GetFeedActivities(ctx context.Context, in *GetFeedActivitiesRequest, opts ...grpc.CallOption) (*GetFeedActivitiesResponse, error)
	UpdateFeed(ctx context.Context, in *UpdateFeedRequest, opts ...grpc.CallOption) (*UpdateFeedResponse, error)
	DeleteFeed(ctx context.Context, in *DeleteFeedRequest, opts ...grpc.CallOption) (*DeleteFeedResponse, error)
	// collections.proto
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	UpdateObject(ctx context.Context, in *UpdateObjectRequest, opts ...grpc.CallOption) (*UpdateObjectResponse, error)
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// reactions.proto
	CreateReaction(ctx context.Context, in *CreateReactionRequest, opts ...grpc.CallOption) (*CreateReactionResponse, error)
	AddReaction(ctx context.Context, in *AddReactionRequest, opts ...grpc.CallOption) (*AddReactionResponse, error)
	GetReaction(ctx context.Context, in *GetReactionRequest, opts ...grpc.CallOption) (*GetReactionResponse, error)
	GetActivityReactions(ctx context.Context, in *GetActivityReactionsRequest, opts ...grpc.CallOption) (*GetActivityReactionsResponse, error)
	UpdateReaction(ctx context.Context, in *UpdateReactionRequest, opts ...grpc.CallOption) (*UpdateReactionResponse, error)
	DeleteReaction(ctx context.Context, in *DeleteReactionRequest, opts ...grpc.CallOption) (*DeleteReactionResponse, error)
	// grouppingFeeds.proto
	CreateGroupingFeed(ctx context.Context, in *CreateGroupingFeedRequest, opts ...grpc.CallOption) (*CreateGroupingFeedResponse, error)
	GetGroupingFeed(ctx context.Context, in *GetGroupingFeedRequest, opts ...grpc.CallOption) (*GetGroupingFeedResponse, error)
	GetGroupingFeedActivities(ctx context.Context, in *GetGroupingFeedActivitiesRequest, opts ...grpc.CallOption) (*GetGroupingFeedActivitiesResponse, error)
	UpdateGroupingFeed(ctx context.Context, in *UpdateGroupingFeedRequest, opts ...grpc.CallOption) (*UpdateGroupingFeedResponse, error)
	DeleteGroupingFeed(ctx context.Context, in *DeleteGroupingFeedRequest, opts ...grpc.CallOption) (*DeleteGroupingFeedResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type feedsClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedsClient(cc grpc.ClientConnInterface) FeedsClient {
	return &feedsClient{cc}
}

func (c *feedsClient) AddActivity(ctx context.Context, in *AddActivityRequest, opts ...grpc.CallOption) (*AddActivityResponse, error) {
	out := new(AddActivityResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/AddActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) AddExistingActivity(ctx context.Context, in *AddExistingActivityRequest, opts ...grpc.CallOption) (*AddExistingActivityResponse, error) {
	out := new(AddExistingActivityResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/AddExistingActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*GetActivityResponse, error) {
	out := new(GetActivityResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetActivityByObjectID(ctx context.Context, in *GetActivityByObjectIDRequest, opts ...grpc.CallOption) (*GetActivityByObjectIDResponse, error) {
	out := new(GetActivityByObjectIDResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetActivityByObjectID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) UpdateActivity(ctx context.Context, in *UpdateActivityRequest, opts ...grpc.CallOption) (*UpdateActivityResponse, error) {
	out := new(UpdateActivityResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/UpdateActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) DeleteActivity(ctx context.Context, in *DeleteActivityRequest, opts ...grpc.CallOption) (*DeleteActivityResponse, error) {
	out := new(DeleteActivityResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/DeleteActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) CreateFeed(ctx context.Context, in *CreateFeedRequest, opts ...grpc.CallOption) (*CreateFeedResponse, error) {
	out := new(CreateFeedResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/CreateFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error) {
	out := new(GetFeedResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetFeedActivities(ctx context.Context, in *GetFeedActivitiesRequest, opts ...grpc.CallOption) (*GetFeedActivitiesResponse, error) {
	out := new(GetFeedActivitiesResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetFeedActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) UpdateFeed(ctx context.Context, in *UpdateFeedRequest, opts ...grpc.CallOption) (*UpdateFeedResponse, error) {
	out := new(UpdateFeedResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/UpdateFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) DeleteFeed(ctx context.Context, in *DeleteFeedRequest, opts ...grpc.CallOption) (*DeleteFeedResponse, error) {
	out := new(DeleteFeedResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/DeleteFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/CreateCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error) {
	out := new(CreateObjectResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/CreateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) UpdateObject(ctx context.Context, in *UpdateObjectRequest, opts ...grpc.CallOption) (*UpdateObjectResponse, error) {
	out := new(UpdateObjectResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/UpdateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/DeleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) CreateReaction(ctx context.Context, in *CreateReactionRequest, opts ...grpc.CallOption) (*CreateReactionResponse, error) {
	out := new(CreateReactionResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/CreateReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) AddReaction(ctx context.Context, in *AddReactionRequest, opts ...grpc.CallOption) (*AddReactionResponse, error) {
	out := new(AddReactionResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/AddReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetReaction(ctx context.Context, in *GetReactionRequest, opts ...grpc.CallOption) (*GetReactionResponse, error) {
	out := new(GetReactionResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetActivityReactions(ctx context.Context, in *GetActivityReactionsRequest, opts ...grpc.CallOption) (*GetActivityReactionsResponse, error) {
	out := new(GetActivityReactionsResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetActivityReactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) UpdateReaction(ctx context.Context, in *UpdateReactionRequest, opts ...grpc.CallOption) (*UpdateReactionResponse, error) {
	out := new(UpdateReactionResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/UpdateReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) DeleteReaction(ctx context.Context, in *DeleteReactionRequest, opts ...grpc.CallOption) (*DeleteReactionResponse, error) {
	out := new(DeleteReactionResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/DeleteReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) CreateGroupingFeed(ctx context.Context, in *CreateGroupingFeedRequest, opts ...grpc.CallOption) (*CreateGroupingFeedResponse, error) {
	out := new(CreateGroupingFeedResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/CreateGroupingFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetGroupingFeed(ctx context.Context, in *GetGroupingFeedRequest, opts ...grpc.CallOption) (*GetGroupingFeedResponse, error) {
	out := new(GetGroupingFeedResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetGroupingFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) GetGroupingFeedActivities(ctx context.Context, in *GetGroupingFeedActivitiesRequest, opts ...grpc.CallOption) (*GetGroupingFeedActivitiesResponse, error) {
	out := new(GetGroupingFeedActivitiesResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/GetGroupingFeedActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) UpdateGroupingFeed(ctx context.Context, in *UpdateGroupingFeedRequest, opts ...grpc.CallOption) (*UpdateGroupingFeedResponse, error) {
	out := new(UpdateGroupingFeedResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/UpdateGroupingFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) DeleteGroupingFeed(ctx context.Context, in *DeleteGroupingFeedRequest, opts ...grpc.CallOption) (*DeleteGroupingFeedResponse, error) {
	out := new(DeleteGroupingFeedResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/DeleteGroupingFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/syntoks_feed.Feeds/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedsServer is the server API for Feeds service.
type FeedsServer interface {
	// activities.proto
	AddActivity(context.Context, *AddActivityRequest) (*AddActivityResponse, error)
	AddExistingActivity(context.Context, *AddExistingActivityRequest) (*AddExistingActivityResponse, error)
	GetActivity(context.Context, *GetActivityRequest) (*GetActivityResponse, error)
	GetActivityByObjectID(context.Context, *GetActivityByObjectIDRequest) (*GetActivityByObjectIDResponse, error)
	UpdateActivity(context.Context, *UpdateActivityRequest) (*UpdateActivityResponse, error)
	DeleteActivity(context.Context, *DeleteActivityRequest) (*DeleteActivityResponse, error)
	// feeds.proto
	CreateFeed(context.Context, *CreateFeedRequest) (*CreateFeedResponse, error)
	GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error)
	GetFeedActivities(context.Context, *GetFeedActivitiesRequest) (*GetFeedActivitiesResponse, error)
	UpdateFeed(context.Context, *UpdateFeedRequest) (*UpdateFeedResponse, error)
	DeleteFeed(context.Context, *DeleteFeedRequest) (*DeleteFeedResponse, error)
	// collections.proto
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	UpdateObject(context.Context, *UpdateObjectRequest) (*UpdateObjectResponse, error)
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// reactions.proto
	CreateReaction(context.Context, *CreateReactionRequest) (*CreateReactionResponse, error)
	AddReaction(context.Context, *AddReactionRequest) (*AddReactionResponse, error)
	GetReaction(context.Context, *GetReactionRequest) (*GetReactionResponse, error)
	GetActivityReactions(context.Context, *GetActivityReactionsRequest) (*GetActivityReactionsResponse, error)
	UpdateReaction(context.Context, *UpdateReactionRequest) (*UpdateReactionResponse, error)
	DeleteReaction(context.Context, *DeleteReactionRequest) (*DeleteReactionResponse, error)
	// grouppingFeeds.proto
	CreateGroupingFeed(context.Context, *CreateGroupingFeedRequest) (*CreateGroupingFeedResponse, error)
	GetGroupingFeed(context.Context, *GetGroupingFeedRequest) (*GetGroupingFeedResponse, error)
	GetGroupingFeedActivities(context.Context, *GetGroupingFeedActivitiesRequest) (*GetGroupingFeedActivitiesResponse, error)
	UpdateGroupingFeed(context.Context, *UpdateGroupingFeedRequest) (*UpdateGroupingFeedResponse, error)
	DeleteGroupingFeed(context.Context, *DeleteGroupingFeedRequest) (*DeleteGroupingFeedResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedFeedsServer can be embedded to have forward compatible implementations.
type UnimplementedFeedsServer struct {
}

func (*UnimplementedFeedsServer) AddActivity(context.Context, *AddActivityRequest) (*AddActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddActivity not implemented")
}
func (*UnimplementedFeedsServer) AddExistingActivity(context.Context, *AddExistingActivityRequest) (*AddExistingActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddExistingActivity not implemented")
}
func (*UnimplementedFeedsServer) GetActivity(context.Context, *GetActivityRequest) (*GetActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}
func (*UnimplementedFeedsServer) GetActivityByObjectID(context.Context, *GetActivityByObjectIDRequest) (*GetActivityByObjectIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityByObjectID not implemented")
}
func (*UnimplementedFeedsServer) UpdateActivity(context.Context, *UpdateActivityRequest) (*UpdateActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateActivity not implemented")
}
func (*UnimplementedFeedsServer) DeleteActivity(context.Context, *DeleteActivityRequest) (*DeleteActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteActivity not implemented")
}
func (*UnimplementedFeedsServer) CreateFeed(context.Context, *CreateFeedRequest) (*CreateFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFeed not implemented")
}
func (*UnimplementedFeedsServer) GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}
func (*UnimplementedFeedsServer) GetFeedActivities(context.Context, *GetFeedActivitiesRequest) (*GetFeedActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedActivities not implemented")
}
func (*UnimplementedFeedsServer) UpdateFeed(context.Context, *UpdateFeedRequest) (*UpdateFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeed not implemented")
}
func (*UnimplementedFeedsServer) DeleteFeed(context.Context, *DeleteFeedRequest) (*DeleteFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFeed not implemented")
}
func (*UnimplementedFeedsServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollection not implemented")
}
func (*UnimplementedFeedsServer) CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObject not implemented")
}
func (*UnimplementedFeedsServer) GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (*UnimplementedFeedsServer) UpdateObject(context.Context, *UpdateObjectRequest) (*UpdateObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateObject not implemented")
}
func (*UnimplementedFeedsServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}
func (*UnimplementedFeedsServer) CreateReaction(context.Context, *CreateReactionRequest) (*CreateReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReaction not implemented")
}
func (*UnimplementedFeedsServer) AddReaction(context.Context, *AddReactionRequest) (*AddReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReaction not implemented")
}
func (*UnimplementedFeedsServer) GetReaction(context.Context, *GetReactionRequest) (*GetReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReaction not implemented")
}
func (*UnimplementedFeedsServer) GetActivityReactions(context.Context, *GetActivityReactionsRequest) (*GetActivityReactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityReactions not implemented")
}
func (*UnimplementedFeedsServer) UpdateReaction(context.Context, *UpdateReactionRequest) (*UpdateReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReaction not implemented")
}
func (*UnimplementedFeedsServer) DeleteReaction(context.Context, *DeleteReactionRequest) (*DeleteReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReaction not implemented")
}
func (*UnimplementedFeedsServer) CreateGroupingFeed(context.Context, *CreateGroupingFeedRequest) (*CreateGroupingFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroupingFeed not implemented")
}
func (*UnimplementedFeedsServer) GetGroupingFeed(context.Context, *GetGroupingFeedRequest) (*GetGroupingFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupingFeed not implemented")
}
func (*UnimplementedFeedsServer) GetGroupingFeedActivities(context.Context, *GetGroupingFeedActivitiesRequest) (*GetGroupingFeedActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupingFeedActivities not implemented")
}
func (*UnimplementedFeedsServer) UpdateGroupingFeed(context.Context, *UpdateGroupingFeedRequest) (*UpdateGroupingFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupingFeed not implemented")
}
func (*UnimplementedFeedsServer) DeleteGroupingFeed(context.Context, *DeleteGroupingFeedRequest) (*DeleteGroupingFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroupingFeed not implemented")
}
func (*UnimplementedFeedsServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterFeedsServer(s *grpc.Server, srv FeedsServer) {
	s.RegisterService(&_Feeds_serviceDesc, srv)
}

func _Feeds_AddActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).AddActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/AddActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).AddActivity(ctx, req.(*AddActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_AddExistingActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExistingActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).AddExistingActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/AddExistingActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).AddExistingActivity(ctx, req.(*AddExistingActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetActivity(ctx, req.(*GetActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetActivityByObjectID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityByObjectIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetActivityByObjectID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetActivityByObjectID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetActivityByObjectID(ctx, req.(*GetActivityByObjectIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_UpdateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).UpdateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/UpdateActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).UpdateActivity(ctx, req.(*UpdateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_DeleteActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).DeleteActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/DeleteActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).DeleteActivity(ctx, req.(*DeleteActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_CreateFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).CreateFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/CreateFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).CreateFeed(ctx, req.(*CreateFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetFeedActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetFeedActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetFeedActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetFeedActivities(ctx, req.(*GetFeedActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_UpdateFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).UpdateFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/UpdateFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).UpdateFeed(ctx, req.(*UpdateFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_DeleteFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).DeleteFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/DeleteFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).DeleteFeed(ctx, req.(*DeleteFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/CreateCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/CreateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).CreateObject(ctx, req.(*CreateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_UpdateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).UpdateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/UpdateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).UpdateObject(ctx, req.(*UpdateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_CreateReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).CreateReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/CreateReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).CreateReaction(ctx, req.(*CreateReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_AddReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).AddReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/AddReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).AddReaction(ctx, req.(*AddReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetReaction(ctx, req.(*GetReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetActivityReactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityReactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetActivityReactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetActivityReactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetActivityReactions(ctx, req.(*GetActivityReactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_UpdateReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).UpdateReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/UpdateReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).UpdateReaction(ctx, req.(*UpdateReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_DeleteReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).DeleteReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/DeleteReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).DeleteReaction(ctx, req.(*DeleteReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_CreateGroupingFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupingFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).CreateGroupingFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/CreateGroupingFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).CreateGroupingFeed(ctx, req.(*CreateGroupingFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetGroupingFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupingFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetGroupingFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetGroupingFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetGroupingFeed(ctx, req.(*GetGroupingFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_GetGroupingFeedActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupingFeedActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).GetGroupingFeedActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/GetGroupingFeedActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).GetGroupingFeedActivities(ctx, req.(*GetGroupingFeedActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_UpdateGroupingFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupingFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).UpdateGroupingFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/UpdateGroupingFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).UpdateGroupingFeed(ctx, req.(*UpdateGroupingFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_DeleteGroupingFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupingFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).DeleteGroupingFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/DeleteGroupingFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).DeleteGroupingFeed(ctx, req.(*DeleteGroupingFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feeds_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syntoks_feed.Feeds/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Feeds_serviceDesc = grpc.ServiceDesc{
	ServiceName: "syntoks_feed.Feeds",
	HandlerType: (*FeedsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddActivity",
			Handler:    _Feeds_AddActivity_Handler,
		},
		{
			MethodName: "AddExistingActivity",
			Handler:    _Feeds_AddExistingActivity_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _Feeds_GetActivity_Handler,
		},
		{
			MethodName: "GetActivityByObjectID",
			Handler:    _Feeds_GetActivityByObjectID_Handler,
		},
		{
			MethodName: "UpdateActivity",
			Handler:    _Feeds_UpdateActivity_Handler,
		},
		{
			MethodName: "DeleteActivity",
			Handler:    _Feeds_DeleteActivity_Handler,
		},
		{
			MethodName: "CreateFeed",
			Handler:    _Feeds_CreateFeed_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _Feeds_GetFeed_Handler,
		},
		{
			MethodName: "GetFeedActivities",
			Handler:    _Feeds_GetFeedActivities_Handler,
		},
		{
			MethodName: "UpdateFeed",
			Handler:    _Feeds_UpdateFeed_Handler,
		},
		{
			MethodName: "DeleteFeed",
			Handler:    _Feeds_DeleteFeed_Handler,
		},
		{
			MethodName: "CreateCollection",
			Handler:    _Feeds_CreateCollection_Handler,
		},
		{
			MethodName: "CreateObject",
			Handler:    _Feeds_CreateObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _Feeds_GetObject_Handler,
		},
		{
			MethodName: "UpdateObject",
			Handler:    _Feeds_UpdateObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _Feeds_DeleteObject_Handler,
		},
		{
			MethodName: "CreateReaction",
			Handler:    _Feeds_CreateReaction_Handler,
		},
		{
			MethodName: "AddReaction",
			Handler:    _Feeds_AddReaction_Handler,
		},
		{
			MethodName: "GetReaction",
			Handler:    _Feeds_GetReaction_Handler,
		},
		{
			MethodName: "GetActivityReactions",
			Handler:    _Feeds_GetActivityReactions_Handler,
		},
		{
			MethodName: "UpdateReaction",
			Handler:    _Feeds_UpdateReaction_Handler,
		},
		{
			MethodName: "DeleteReaction",
			Handler:    _Feeds_DeleteReaction_Handler,
		},
		{
			MethodName: "CreateGroupingFeed",
			Handler:    _Feeds_CreateGroupingFeed_Handler,
		},
		{
			MethodName: "GetGroupingFeed",
			Handler:    _Feeds_GetGroupingFeed_Handler,
		},
		{
			MethodName: "GetGroupingFeedActivities",
			Handler:    _Feeds_GetGroupingFeedActivities_Handler,
		},
		{
			MethodName: "UpdateGroupingFeed",
			Handler:    _Feeds_UpdateGroupingFeed_Handler,
		},
		{
			MethodName: "DeleteGroupingFeed",
			Handler:    _Feeds_DeleteGroupingFeed_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Feeds_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service.proto",
}
